### ISSUE TITLE
Prune

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/Delete#6]
Bulk delete files with expiring date passed

**Comment by NeillGiraldo** [comment]
Due to the conclusion written here 
    http://stackoverflow.com/questions/25639221/how-to-run-recurring-task-in-the-python-flask-framework

Schedulers should not be tied to the flask app, that is why it is necessary to call the recurring task in other place... can we do this in the api_gateway @maasencioh ? Notice that all the business-logic regarding deleting files would be in place ( in delete_ms)

**Comment by maasencioh** [comment]
yes, remember that the idea is just to implement the function and that the api_gateway only have to call this method each day
